# Generated by Django 3.1.2 on 2021-01-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210103_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
