# Generated by Django 3.1.2 on 2021-01-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210103_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
